### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by samuelcastro** [UnlyEd/GraphCMS-cache-boilerplate#16]
Hi, first of all, great job, it's really rare to find out really read-to-production projects out there totally open-source, I really appreciate the time and effort you put on this and also on Next Right Now.

A few things:

- I'd rename this project to something else, maybe: `graphql-cache-boirlerplate` or something, I haven't cloned the project yet but as far as I understand it could be used to others providers as well.
- What's the status of it, are you still maintaining it periodically, I saw that the last commit as 7 months ago or so?

I might be using this along with NRN in a big project and I'd love to contribute if we really decide to use it.

Once again, great job!

**Comment by Vadorequest** [comment]
Hello @samuelcastro :) 

The status of the project is production-ready, there isn't much that is needed on our side so we don't add more features but it's used in production and helps power websites such as https://solidarity.unly.org/

I hesitated with the repository name, but because we support right from the core some GraphCMS features (such as specific headers for i18n) and because I've only tested it against GraphCMS, I believe the name is alright. _(using "graphql" may be better for other to find the project, but I assume that's what github tags are here for)_

Indeed, it may be used by any GraphQL powered backend, the provider really doesn't matter.

Don't hesitate to contribute about the documentation if things are unclear.

**Comment by samuelcastro** [comment]
Thanks for the update, I thought you were using this on NRN but I can't find it there, do you have a different preset for it?

**Comment by Vadorequest** [comment]
I'm not using it with NRN, because it hardens the "getting started". Also, it's very specific to a particular usage and doesn't fit all business, so it's more of a side thing for people who are looking for it, specifically.

There isn't much to do, the most complicated part is to setup your domain name really (and SSL certificate) if you do use a custom domain.

Otherwise, it's just a matter of replacing a graphql endpoint (e.g: GraphCMS) by another one (this cache) on your frontend app, that's it.

**Comment by Vadorequest** [comment]
Basically, the "demo" app can be duplicated by following https://github.com/UnlyEd/GraphCMS-cache-boilerplate#how-to-deploy-a-new-customer and that's enough to setup a new "customer" (this boilerplate is multi-tenants by design, so you can manage multiple caches from the same repo)

**Comment by samuelcastro** [comment]
Got it.
